### ISSUE TITLE
Share now sample fails to provision with Failed to create user error

### ISSUE THREAD

**Issue by therealjohn** [OfficeDev/TeamsFx-Samples#513] opened 2022-10-18 20:59 UTC
Following the steps to Provision, it fails with this error: 

> [Error] - code:SQL.DatabaseUserCreateError, message: Failed to create user 'sharenowdev2f4ef03' in database (sharenowdev2f4ef03)Reason: Could not retrieve the token associated with Visual Studio Code. Did you connect using the 'Azure Account' extension?. You can follow https://aka.ms/teamsfx-sql-help to handle it.

**Comment by xzf0587** [comment] 2022-10-19 06:10
Hi @therealjohn,
Thank you for reaching out. This is a known issue caused by Azure account extension of vscode. 
We have triaged it in [teamsfx toolkit repository](https://github.com/OfficeDev/TeamsFx/issues/3971).
Current work around by Azure account extension downgrade:
1. Downgrade Azure account extension to 0.9.11 and close auto update.
2. Sign in azure account and provision.

**Comment by xzf0587** [comment] 2022-10-27 01:44
Hi @therealjohn,
Thanks for sharing this information. Close this issue to keep clean. You can reopen it if there is further question.

**Closed by xzf0587** 2022-10-27 01:44 UTC
